import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE
If you want to view the source, visit the plugins github repository
https://github.com/ozntel/oz-image-in-editor-obsidian
*/
`;

const prod = process.argv[2] === 'production';

esbuild
    .build({
        banner: {
            js: banner,
        },
        minify: prod ? true : false,
        entryPoints: ['src/main.ts'],
        bundle: true,
        external: [
            'obsidian',
            'electron',
            'codemirror',
            '@codemirror/autocomplete',
            '@codemirror/commands',
            '@codemirror/lang-css',
            '@codemirror/lang-html',
            '@codemirror/language',
            '@codemirror/lint',
            '@codemirror/search',
            '@codemirror/state',
            '@codemirror/view',
            ...builtins,
        ],
        format: 'cjs',
        watch: !prod,
        target: 'es2016',
        logLevel: 'info',
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        outfile: 'dist/main.js',
    })
    .catch(() => process.exit(1));
